{
 "title": "Reddit-Stock Price Sentiment Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "selected_ticker", "label": "Selected Ticker", "query": "AAPL,MSFT,TSLA" }
  ]
 },
 "panels": [
  {
   "title": "reddit comment sentiment:",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "keyspace": "stockprices",
     "target": "SELECT body_sentiment_score AS \"Most Recent\"\nFROM redditcomments.output_data\nWHERE ticker = '$selected_ticker' \nLIMIT 1;"
    },
    {
     "keyspace": "redditcomments",
     "target": "SELECT AVG(body_sentiment_score) AS \"Prior 30 Minutes\"\nFROM redditcomments.output_data\nWHERE ticker = '$selected_ticker' AND created_utc > toTimestamp(now()) - 30m;"
    },
    {
     "keyspace": "redditsubmissions",
     "target": "SELECT AVG(body_sentiment_score) AS \"Prior 1 Hour\"\nFROM redditcomments.output_data\nWHERE ticker = '$selected_ticker' AND created_utc > toTimestamp(now()) - 60m ;"
    },
    {
     "keyspace": "redditcomments",
     "target": "SELECT AVG(body_sentiment_score) AS \"Prior 2 Hours\"\nFROM redditcomments.output_data\nWHERE ticker = '$selected_ticker' AND created_utc > toTimestamp(now()) - 120m ;"
    },
    {
     "keyspace": "redditcomments",
     "target": "SELECT AVG(body_sentiment_score) AS \"Prior 4 Hours\"\nFROM redditcomments.output_data\nWHERE ticker = '$selected_ticker' AND created_utc > toTimestamp(now()) - 480m ;"
    }
   ]
  },
  {
   "title": "latest price:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "keyspace": "stockprices",
     "target": "SELECT symbol AS \"symbol:\", price AS \"price:\", timestamp AS \"as of:\"\nFROM stockprices.output_data \nWHERE symbol = '$selected_ticker' \nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "price change:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "keyspace": "stockprices",
     "target": "SELECT symbol, price AS \"price change:\"\nFROM stockprices.output_data \nWHERE symbol = '$selected_ticker' \nORDER BY timestamp DESC\nLIMIT 2;"
    }
   ]
  },
  {
   "title": "Reddit Comment Sentiment",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "keyspace": "redditsubmissions",
     "target": "SELECT ticker, created_utc,  body, body_sentiment_score, subreddit\nFROM redditcomments.output_data\nWHERE ticker = '$selected_ticker'\nAND created_utc >= toTimestamp(now()) - 180m;;"
    }
   ]
  },
  {
   "title": "Stock Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "keyspace": "stockprices",
     "target": "SELECT symbol, timestamp, price \nFROM stockprices.output_data \nWHERE symbol = '$selected_ticker' \nAND timestamp >= toTimestamp(now()) - 120m;"
    }
   ]
  },
  {
   "title": "Reddit Comment Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "{{ticker}}",
     "keyspace": "redditsubmissions",
     "target": "SELECT ticker, COUNT(ticker) as cnt\nFROM redditcomments.output_data\nWHERE ticker = 'TSLA'\nGROUP BY ticker;"
    },
    {
     "alias": "{{ticker}}",
     "keyspace": "redditcomments",
     "target": "SELECT ticker, COUNT(ticker) as cnt\nFROM redditcomments.output_data\nWHERE ticker = 'AAPL'\nGROUP BY ticker;"
    },
    {
     "alias": "{{ticker}}",
     "keyspace": "redditcomments",
     "target": "SELECT ticker, COUNT(ticker) as cnt\nFROM redditcomments.output_data\nWHERE ticker = 'INTC'\nGROUP BY ticker;"
    },
    {
     "alias": "{{ticker}}",
     "keyspace": "redditcomments",
     "target": "SELECT ticker, COUNT(ticker) as cnt\nFROM redditcomments.output_data\nWHERE ticker = 'MSFT'\nGROUP BY ticker;"
    }
   ]
  },
  {
   "title": "Trading Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "keyspace": "stockprices",
     "target": "SELECT symbol, timestamp, volume\nFROM stockprices.output_data\nWHERE symbol = '$selected_ticker' \nAND timestamp >= toTimestamp(now()) - 120m;"
    }
   ]
  }
 ]
}